# Generated by Django 3.2.7 on 2021-09-19 13:29

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18)),
                ('razao_social', models.CharField(max_length=500)),
                ('fantasia', models.CharField(max_length=500)),
                ('bool_master', models.BooleanField()),
                ('inscricao_estadual', models.IntegerField()),
                ('num_empregados', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dt_ano_inicio', models.DateField()),
                ('projeto', models.CharField(max_length=500)),
                ('nome_gestor', models.CharField(max_length=500)),
                ('ds_negocio', models.CharField(max_length=500)),
                ('bool_missao', models.BooleanField()),
                ('missao', models.CharField(blank=True, max_length=500)),
                ('bool_visao', models.BooleanField()),
                ('visao', models.CharField(blank=True, max_length=500)),
                ('bool_valores', models.BooleanField()),
                ('valores', models.CharField(blank=True, max_length=500)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('logradouro', models.CharField(max_length=500)),
                ('endereco', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FaseProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fase', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_perfil', models.CharField(max_length=500)),
                ('bool_admin', models.BooleanField()),
                ('bool_excluido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_segmento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_setor', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_situacao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('tipo_telefone', models.CharField(choices=[('CEL', 'Celular'), ('FIX', 'Fixo'), ('FAX', 'Fax')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_diagnostico', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndustria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_tipo_industria', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_uf', models.CharField(max_length=2)),
                ('nome_uf', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ValorArrecadacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_valor_arrecadacao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.situacao')),
                ('telefone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.telefone')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.uf')),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ano', models.DateField()),
                ('valor', models.IntegerField()),
                ('fk_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.segmento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.setor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_tipo_industria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.tipoindustria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_tipo_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_valor_arrecadacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.valorarrecadacao'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.grupo'),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ano', models.DateField()),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.faseprojeto')),
                ('fk_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.empresa')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.tipodiagnostico')),
            ],
        ),
    ]
