# Generated by Django 3.2.7 on 2021-09-25 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('M2A_app', '0001_initial'),
    ]

    operations = [
    ]
