# Generated by Django 3.2.7 on 2021-09-25 01:08

from django.db import migrations
from ..models import *


def seed_uf():
    UF.objects.bulk_create([
        UF('AM', 'Amazonas'),
    ])


def seed_setor():
    Setor.objects.bulk_create([
        Setor('Agronegócio'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('M2A_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_uf),
        migrations.RunPython(seed_setor)
    ]
