# Generated by Django 3.2.7 on 2021-09-25 01:08

from django.db import migrations
from ..models import *


def seed_uf():
    UF.objects.bulk_create([
        UF('AC', 'Acre'),
        UF('AL', 'Alagoas'),
        UF('AP', 'Amapá'),
        UF('AM', 'Amazonas'),
        UF('BA', 'Bahia'),
        UF('CE', 'Ceará'),
        UF('DF', 'Distrito Federal'),
        UF('ES', 'Espírito Santo'),
        UF('GO', 'Goiás'),
        UF('MA', 'Maranhão'),
        UF('MT', 'Mato Grosso'),
        UF('MS', 'Mato Grosso do Sul'),
        UF('MG', 'Minas Gerais'),
        UF('PA', 'Pará'),
        UF('PB', 'Paraíba'),
        UF('PR', 'Paraná'),
        UF('PE', 'Pernambuco'),
        UF('PI', 'Piauí'),
        UF('RJ', 'Rio de Janeiro'),
        UF('RN', 'Rio Grande do Norte'),
        UF('RS', 'Rio Grande do Sul'),
        UF('RO', 'Rondônia'),
        UF('RR', 'Roraima'),
        UF('SC', 'Santa Catarina'),
        UF('SP', 'São Paulo'),
        UF('SE', 'Sergipe'),
        UF('TO', 'Tocantins'),
        UF('EX', 'Estrangeiro'),
    ])


def seed_setor():
    Setor.objects.bulk_create([
        Setor('Agronegócio'),
        Setor('Análise Clínica'),
        Setor('Comércio'),
        Setor('Indústria'),
        Setor('Micro e Pequenas Empresas'),
        Setor('Serviços'),
        Setor('Serviços de Tecnologia da Informação'),
        Setor('Serviços de Turismo'),
        Setor('Serviços Financeiros'),
        Setor('Outro'),
    ])
    
def seed_segmento():
    Segmento.objects.bulk_create([
        Segmento('Adestramento'),
        Segmento('Agrícultura e Pesca'),
        Segmento('Agroenergia'),
        Segmento('Agronegócio'),
        Segmento('Alimentação'),
        Segmento('Aluguel de Espaço Físico'),
        Segmento('Apicultura'),
        Segmento('Artesanato'),
        Segmento('Biotecnologia'),
        Segmento('Borracharia'),
        Segmento('Café'),
        Segmento('Carne'),
        Segmento('Comércio Varejista'),
        Segmento('Construção Civil'),
        Segmento('Consultoria Comercial'),
        Segmento('Consultoria Empresarial'),
        Segmento('Cosméticos'),
        Segmento('Couro e Calçados'),
        Segmento('Cultura e Entretenimento'),
        Segmento('Derivados de Cana'),
        Segmento('Economia Criativa'),
        Segmento('Estética'),
        Segmento('Fabr. de Prod. de Padaria e Confeitaria'),
        Segmento('Floricultura'),
        Segmento('Fruticultura'),
        Segmento('Horticultura'),
        Segmento('Leite e Derivados'),
        Segmento('Madeira e Móveis'),
        Segmento('Mandiocultura'),
        Segmento('Material de Construção'),
        Segmento('MEI'),
        Segmento('Metal Mecânica'),
        Segmento('Moda'),
        Segmento('Não Informado'),
        Segmento('Ovinocaprinocultura'),
        Segmento('Pet Shop'),
        Segmento('Petróleo e Gás'),
        Segmento('Pizzaria'),
        Segmento('Química e Plásticos'),
        Segmento('Rochas Ornamentais'),
        Segmento('Salão de Beleza'),
        Segmento('Serviços'),
        Segmento('Serviços Financeiros'),
        Segmento('Serviços Médicos'),
        Segmento('Sindicato'),
        Segmento('Tecnologia da Informação'),
        Segmento('Têxtil e Confecções'),
        Segmento('Turismo'),
        Segmento('Outro'),
    ])

def seed_valorArrecadacao():
    ValorArrecadacao.objects.bulk_create([
        ValorArrecadacao('MEI - até R$60 mil'),
        ValorArrecadacao('0 até R$360 mil'),
        ValorArrecadacao('R$360 até R$3.600 mil'),
        ValorArrecadacao('R$3.600 mil até R$5 milhões'),
        ValorArrecadacao('Acima de R$5 milhões'),
    ])

def seed_tipoIndustria():
    TipoIndustria.objects.bulk_create([
        TipoIndustria('Associação/Cooperativa'),
        TipoIndustria('Cliente'),
        TipoIndustria('Filial'),
        TipoIndustria('Fornecedor'),
        TipoIndustria('Franquia'),
        TipoIndustria('Matriz'),
        TipoIndustria('Outros'),
    ])

def seed_situacao():
    Situacao.objects.bulk_create([
        Situacao('Ativo'),
        Situacao('Inativo'),
    ])

def seed_tipoDiagnostico():
    TipoDiagnostico.objects.bulk_create([
        TipoDiagnostico('Simples'),
        TipoDiagnostico('Completo'),
    ])

def seed_faseProjeto():
    FaseProjeto.objects.bulk_create([
        FaseProjeto('T0'),
        FaseProjeto('T1'),
        FaseProjeto('T2'),
        FaseProjeto('T3'),
        FaseProjeto('T4'),
        FaseProjeto('T5'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('M2A_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_uf),
        migrations.RunPython(seed_setor)
    ]
