# Generated by Django 3.2.7 on 2021-09-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0002_seed_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='fk_tipo_master',
            new_name='fk_master',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.uf'),
        ),
    ]
