# Generated by Django 3.2.8 on 2021-10-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0003_auto_20210926_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fk_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.empresa'),
        ),
    ]
