# Generated by Django 3.2.8 on 2021-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0004_alter_empresa_fk_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fk_celular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celular', to='M2A_app.telefone'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_fax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fax', to='M2A_app.telefone'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_telefone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefone_empresa', to='M2A_app.telefone'),
        ),
    ]
