# Generated by Django 3.2.8 on 2021-10-20 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0005_auto_20211019_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='grupo',
            new_name='fk_grupo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fk_celular',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fk_fax',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fk_telefone',
        ),
        migrations.AddField(
            model_name='empresa',
            name='celular',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dt_nascimento_responsavel',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_responsavel',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='fax',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='formacao_responavel',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Primeiro grau', 'Primeiro grau'), ('Segundo grau', 'Segundo grau'), ('Superior', 'Superior'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado e Doutorado', 'Mestrado e Doutorado')], default='Analfabeto', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone_gestor',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
