# Generated by Django 3.2.8 on 2021-10-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0007_auto_20211019_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
    ]
