# Generated by Django 3.2.8 on 2021-10-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0009_alter_empresa_inscricao_estadual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='formacao_responavel',
            new_name='formacao_responsavel',
        ),
        migrations.AddField(
            model_name='empresa',
            name='sexo_responsavel',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Analfabeto', max_length=500),
            preserve_default=False,
        ),
    ]
