# Generated by Django 3.2.8 on 2021-10-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0010_auto_20211019_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_responsavel',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fantasia',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='fk_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamentos', to='M2A_app.empresa'),
        ),
    ]
