# Generated by Django 3.2.8 on 2021-10-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0013_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
