# Generated by Django 3.2.8 on 2021-11-26 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0018_diagnostico_fk_consultor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='usuario',
            new_name='consultor_master',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='dt_nascimento_responsavel',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email_responsavel',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='formacao_responsavel',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome_gestor',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome_responsavel',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sexo_responsavel',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefone_gestor',
        ),
        migrations.AddField(
            model_name='usuarioinfo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.empresa'),
        ),
        migrations.AddField(
            model_name='usuarioinfo',
            name='formacao_responsavel',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Primeiro grau', 'Primeiro grau'), ('Segundo grau', 'Segundo grau'), ('Superior', 'Superior'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado e Doutorado', 'Mestrado e Doutorado')], default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.projeto'),
        ),
    ]
