# Generated by Django 3.2.8 on 2021-11-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0019_auto_20211126_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fundamento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=500)),
                ('fundamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M2A_app.fundamento')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='projeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.projeto'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('valor', models.IntegerField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M2A_app.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M2A_app.empresa')),
            ],
        ),
    ]
