# Generated by Django 3.2.8 on 2021-11-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0021_pergunta_questionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='texto',
            new_name='texto_resposta',
        ),
    ]
