# Generated by Django 3.2.8 on 2021-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0025_auto_20211127_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='questionario',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='questionario',
            field=models.ManyToManyField(related_name='perguntas', to='M2A_app.Questionario'),
        ),
    ]
