# Generated by Django 3.2.8 on 2021-11-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0026_auto_20211128_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='empresa_master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='M2A_app.empresa'),
        ),
    ]
