# Generated by Django 3.2.8 on 2021-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0027_alter_questionario_empresa_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fase',
            field=models.CharField(max_length=500),
        ),
    ]
