# Generated by Django 3.2.8 on 2021-11-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0028_alter_diagnostico_fase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='consultor_master',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='respostaquestionario',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='M2A_app.diagnostico'),
        ),
    ]
