# Generated by Django 3.2.8 on 2021-11-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0029_auto_20211128_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
    ]
