# Generated by Django 3.2.8 on 2021-11-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M2A_app', '0030_remove_empresa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='M2A_app.projeto'),
        ),
    ]
